# SDL
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/bin/include
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/bin/include/SDL2

FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/LIBS/SDL_image/include
# FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/src/haptic

# libretro-common
FLAGS += -I$(CORE_DIR)/vendor/libretro-common/include \
	-DHAVE_RWAV=1
# Only compile libretro-common when not STATIC_LINKING
ifneq ($(STATIC_LINKING), 1)
	SOURCES_C += $(wildcard \
		$(CORE_DIR)/vendor/libretro-common/audio/audio_mix.c \
		$(CORE_DIR)/vendor/libretro-common/audio/audio_mixer.c \
		$(CORE_DIR)/vendor/libretro-common/audio/conversion/*.c \
		$(CORE_DIR)/vendor/libretro-common/audio/resampler/audio_resampler.c \
		$(CORE_DIR)/vendor/libretro-common/audio/resampler/drivers/nearest_resampler.c \
		$(CORE_DIR)/vendor/libretro-common/audio/resampler/drivers/null_resampler.c \
		$(CORE_DIR)/vendor/libretro-common/audio/resampler/drivers/sinc_resampler.c \
		$(CORE_DIR)/vendor/libretro-common/compat/compat_posix_string.c \
		$(CORE_DIR)/vendor/libretro-common/compat/compat_strcasestr.c \
		$(CORE_DIR)/vendor/libretro-common/compat/compat_strl.c \
		$(CORE_DIR)/vendor/libretro-common/compat/fopen_utf8.c \
		$(CORE_DIR)/vendor/libretro-common/encodings/encoding_utf.c \
		$(CORE_DIR)/vendor/libretro-common/features/features_cpu.c \
		$(CORE_DIR)/vendor/libretro-common/file/config_file.c \
		$(CORE_DIR)/vendor/libretro-common/file/config_file_userdata.c \
		$(CORE_DIR)/vendor/libretro-common/file/file_path.c \
		$(CORE_DIR)/vendor/libretro-common/file/file_path_io.c \
		$(CORE_DIR)/vendor/libretro-common/file/retro_dirent.c \
		$(CORE_DIR)/vendor/libretro-common/time/rtime.c \
		$(CORE_DIR)/vendor/libretro-common/formats/wav/rwav.c \
		$(CORE_DIR)/vendor/libretro-common/lists/string_list.c \
		$(CORE_DIR)/vendor/libretro-common/memmap/memalign.c \
		$(CORE_DIR)/vendor/libretro-common/rthreads/rthreads.c \
		$(CORE_DIR)/vendor/libretro-common/streams/file_stream.c \
		$(CORE_DIR)/vendor/libretro-common/string/stdstring.c \
		$(CORE_DIR)/vendor/libretro-common/vfs/vfs_implementation.c \
	)
    # Ensure the sinc_resampler_neon is available for ARM NEON devices.
	SOURCES_S += $(CORE_DIR)/vendor/libretro-common/audio/resampler/drivers/sinc_resampler_neon.S
	
	

    # MD5
    
    SOURCES_C += $(CORE_DIR)/vendor/libretro-common/utils/md5.c
endif

ifeq ($(platform), ctr)
     SOURCES_C += $(CORE_DIR)/vendor/libretro-common/audio/audio_mix.c \
       $(CORE_DIR)/vendor/libretro-common/audio/audio_mixer.c
endif

ifeq ($(platform), emscripten)
     SOURCES_C += $(CORE_DIR)/vendor/libretro-common/rthreads/rthreads.c
endif

ifeq ($(platform), win)
	SOURCES_C += $(wildcard \
	./vendor/sdl2-libretro/src/thread/generic/*.c \
	./vendor/sdl2-libretro/src/core/windows/*.c \
	./vendor/sdl2-libretro/src/timer/windows/*.c \
	./vendor/sdl2-libretro/src/timer/*.c \
	./vendor/sdl2-libretro/src/*.c \
	./vendor/sdl2-libretro/src/thread/*.c \
	./vendor/sdl2-libretro/src/cdrom/dummy/*.c \
	./vendor/sdl2-libretro/src/cdrom/*.c \
	./vendor/sdl2-libretro/src/cpuinfo/*.c \
	./vendor/sdl2-libretro/src/stdlib/*.c \
	./vendor/sdl2-libretro/src/nojoystick/*.c \
	./vendor/sdl2-libretro/src/nojoystick/libretro/*.c \
	./vendor/sdl2-libretro/src/loadso/windows/*.c \
	./vendor/sdl2-libretro/src/audio/libretro/*.c \
	./vendor/sdl2-libretro/src/timer/libretro/*.c \
	./vendor/sdl2-libretro/src/audio/*.c \
	./vendor/sdl2-libretro/src/audio/dummy_libretro/*.c \
	./vendor/sdl2-libretro/src/events/*.c \
	./vendor/sdl2-libretro/src/video/*.c \
	./vendor/sdl2-libretro/src/video/windows/*.c \
	./vendor/sdl2-libretro/src/file/*.c)
else
	SOURCES_C += $(wildcard \
		$(CORE_DIR)/vendor/sdl2-libretro/src/*.c \
		$(CORE_DIR)/vendor/sdl2-libretro/src/audio/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/cdrom/dummy/*.c \
		$(CORE_DIR)/vendor/sdl2-libretro/src/cdrom/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/cpuinfo/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/events/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/file/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/stdlib/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/thread/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/timer/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/video/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/nojoystick/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/video/dummy_libretro/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/thread/generic/*.c \
		$(CORE_DIR)/vendor/sdl2-libretro/src/nojoystick/libretro/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/timer/libretro/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/audio/libretro/*.c  \
		$(CORE_DIR)/vendor/sdl2-libretro/src/loadso/dummy/*.c)
endif
FLAGS += -DSDL_THREADS_DISABLED -DSDL_CDROM_DISABLED
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/include

# SDL_gfx
# FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/src/video/libretro
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/src/video/khronos
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/src/video/windows
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/test_sdlgfx
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/src/render/software
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/src/render/vulkan
SOURCES_C += $(wildcard \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/LIBS/SDL2_gfx-1.0.3/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/LIBS/SDL2_ttf-2.0.14/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/LIBS/SDL_image/src/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/LIBS/SDL_image/external/jpeg/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/LIBS/SDL_image/external/libpng/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/LIBS/SDL_image/external/libpng/arm/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/src/render/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/src/render/software/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/src/render/vulkan/*.c \
	$(CORE_DIR)/vendor/sdl2-libretro/src/atomic/*.c \
	$(CORE_DIR)/vendor/physfs/extras/physfsrwops.c \
	$(CORE_DIR)/src/love/data/libraries/lz4/*.c \
	$(CORE_DIR)/vendor/physfs/src/*.c \
	$(CORE_DIR)/src/love/libraries/xxHash/*.c \
)
#   $(CORE_DIR)/vendor/sdl2-libretro/src/timer/*.c \
# 	$(CORE_DIR)/vendor/sdl2-libretro/src/timer/dummy_libretro/*.c \
# 	$(CORE_DIR)/vendor/sdl2-libretro/src/video/*.c \
# 	$(CORE_DIR)/vendor/sdl2-libretro/src/video/dummy_libretro/*.c \
# 	$(CORE_DIR)/vendor/sdl2-libretro/src/thread/*.c \
# 	$(CORE_DIR)/vendor/sdl2-libretro/src/stdlib/*.c \
# 	$(CORE_DIR)/vendor/sdl2-libretro/src/audio/*.c \
# 	$(CORE_DIR)/vendor/sdl2-libretro/src/audio/dummy/*.c \
# 	$(CORE_DIR)/vendor/sdl2-libretro/src/file/*.c \
#	$(CORE_DIR)/vendor/sdl2-libretro/src/thread/*.c \

# $(CORE_DIR)/vendor/sdl2-libretro/src/joystick/*.c \

# ChaiLove
SOURCES_CXX := $(wildcard \
	$(CORE_DIR)/src/*.cpp \
	$(CORE_DIR)/src/love/*.cpp \
	$(CORE_DIR)/src/love/Types/Audio/*.cpp \
	$(CORE_DIR)/src/love/Types/Config/*.cpp \
	$(CORE_DIR)/src/love/Types/FileSystem/*.cpp \
	$(CORE_DIR)/src/love/Types/Graphics/*.cpp \
	$(CORE_DIR)/src/love/Types/Input/*.cpp \
	$(CORE_DIR)/src/love/audio/*.cpp \
	$(CORE_DIR)/src/love/audio/null/*.cpp \
	$(CORE_DIR)/src/love/audio/openal/*.cpp \
	$(CORE_DIR)/src/love/common/*.cpp \
	$(CORE_DIR)/src/love/data/*.cpp \
	$(CORE_DIR)/src/love/filesystem/*.cpp \
	$(CORE_DIR)/src/love/filesystem/physfs/*.cpp \
	$(CORE_DIR)/src/love/font/*.cpp \
	$(CORE_DIR)/src/love/font/freetype/*.cpp \
	$(CORE_DIR)/src/love/font/libraries/*.cpp \
	$(CORE_DIR)/src/love/font/libraries/utf8/*.cpp \
	$(CORE_DIR)/src/love/image/*.cpp \
	$(CORE_DIR)/src/love/image/magpie/*.cpp \
	$(CORE_DIR)/src/love/math/*.cpp \
	$(CORE_DIR)/src/love/vulkan/*.cpp \
	$(CORE_DIR)/src/love/sound/*.cpp \
	$(CORE_DIR)/src/love/sound/lullaby/*.cpp \
	$(CORE_DIR)/src/love/thread/*.cpp \
	$(CORE_DIR)/src/love/thread/sdl/*.cpp \
	$(CORE_DIR)/src/love/timer/*.cpp \
	$(CORE_DIR)/src/love/video/*.cpp \
	$(CORE_DIR)/src/love/video/theora/*.cpp \
	$(CORE_DIR)/src/love/window/*.cpp \
	$(CORE_DIR)/src/love/window/sdl/*.cpp \
	$(CORE_DIR)/src/love/image/magpie/*.cpp \
	$(CORE_DIR)/src/love/image/magpie/ddsparse/*.cpp \
	$(CORE_DIR)/src/love/libraries/glslang/glslang/MachineIndependent/*.cpp \
	$(CORE_DIR)/src/love/libraries/glslang/glslang/MachineIndependent/preprocessor/*.cpp \
	$(CORE_DIR)/src/love/libraries/glslang/glslang/ResourceLimits/*.cpp \
	$(CORE_DIR)/src/love/libraries/glslang/glslang/GenericCodeGen/*.cpp \
	$(CORE_DIR)/src/love/libraries/glslang/SPIRV/*.cpp \
	$(CORE_DIR)/src/love/libraries/lodepng/*.cpp \
	$(CORE_DIR)/src/love/vulkan/spirv_cross/*.cpp \
)
SOURCES_C += $(CORE_DIR)/src/physfs_platform_libretro.c
SOURCES_S =
FLAGS += -Wfatal-errors

# LOVE
FLAGS += -I$(CORE_DIR)/src/love/libraries/tinyexr
FLAGS += -I$(CORE_DIR)/src/love/libraries/lodepng

# glslang

FLAGS += -I$(CORE_DIR)/src/love/libraries/glslang/SPIRV
FLAGS += -I$(CORE_DIR)/src/love/libraries/glslang/glslang/Include
FLAGS += -I$(CORE_DIR)/src/love/libraries/glslang/glslang/Public
FLAGS += -I$(CORE_DIR)/src/love/libraries/glslang/glslang/MachineIndependent

# FLAGS += -I$(CORE_DIR)/src/love/joystick/sdl

# random
FLAGS += -I$(CORE_DIR)/vendor/random/include

# stb_vorbis
#SOURCES_C += $(CORE_DIR)/vendor/stb/stb_vorbis.c
FLAGS += -DHAVE_STB_VORBIS
FLAGS += -I$(CORE_DIR)/vendor/libretro-deps

# zlib
SOURCES_C += \
	$(CORE_DIR)/vendor/libretro-deps/libz/adler32.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/compress.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/crc32.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/deflate.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/gzclose.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/gzlib.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/gzread.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/gzwrite.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/infback.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/inffast.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/inflate.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/inftrees.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/trees.c \
	$(CORE_DIR)/vendor/libretro-deps/libz/zutil.c
FLAGS += -I$(CORE_DIR)/vendor/libretro-deps/libz
FLAGS += -I$(CORE_DIR)/vendor/libretro-common/compat
FLAGS += -DWANT_ZLIB

# FLAGS += -DPPM_SUPPORTED
# FLAGS += -DUSE_STBIMAGE
# FLAGS += -DSDL_IMAGE_SAVE_JPG=0
# FLAGS += -DFAST_IS_JPEG
# FLAGS += -DFAST_IS_PNG
# FLAGS += -DWANT_JPEGLIB
# FLAGS += -DWANT_PNGLIB

# # PhysFS
FLAGS += -I$(CORE_DIR)/vendor/physfs/src
FLAGS += -I$(CORE_DIR)/vendor/physfs/extras
# FLAGS += -DPHYSFS_NO_CDROM_SUPPORT=1 \
# 	-DPHYSFS_SUPPORTS_DEFAULT=0 \
# 	-DPHYSFS_SUPPORTS_ZIP=1

# SOURCES_C += $(wildcard \
# 	$(CORE_DIR)/vendor/physfs/extras/physfsrwops.c \
# 	$(CORE_DIR)/vendor/physfs/src/*.c \
# )
# ifeq ($(platform), osx)
# #	LDFLAGS += -mmacosx-version-min=10.2
# 	LDFLAGS += -framework IOKit -framework Foundation
# #	FLAGS += -DMAC_OS_X_VERSION_MIN_REQUIRED=1020
# 	FLAGS += -D__MACH__ -D__APPLE__ -DPHYSFS_PLATFORM_APPLE
# endif

# FLAGS += -I$(CORE_DIR)/vendor/libretro-common/include/glsm
# FLAGS += -I$(CORE_DIR)/vendor/libretro-common/include/glsym

FLAGS += -I$(CORE_DIR)/vendor/libretro-common/include/vulkan
FLAGS += -I$(CORE_DIR)/src/love/vulkan/vulkanheaders

# SDL_tty
FLAGS += -I$(CORE_DIR)/vendor/SDL2_tty/include/SDL_tty
SOURCES_C += $(wildcard \
	$(CORE_DIR)/vendor/SDL2_tty/src/SDL_fnt.c \
	$(CORE_DIR)/vendor/SDL2_tty/src/SDL_tty.c \
)

# PortableGL
# FLAGS += -I$(CORE_DIR)/vendor/PortableGL
# FLAGS += -I$(CORE_DIR)/vendor/PortableGL/external/glm/glm
# FLAGS += -I$(CORE_DIR)/vendor/PortableGL/src
# FLAGS += -I$(CORE_DIR)/vendor/PortableGL/glcommon
# FLAGS += -I$(CORE_DIR)/vendor/GLTools/include
# FLAGS += -I/usr/share/R/include
# FLAGS += -I/usr/include/open3d/geometry
# FLAGS += -I/usr/include/eigen3
# FLAGS += -DUSING_PORTABLEGL
# SOURCES_C += $(wildcard \
# 	$(CORE_DIR)/src/pgl.c \
# )

# FreeType2
# See https://github.com/emscripten-ports/FreeType/blob/master/builds/amiga/makefile
FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/LIBS/SDL2_ttf-2.0.14/external/freetype-2.4.12/include
FLAGS += -DFT2_BUILD_LIBRARY \
	-DFT_USE_AUTOFIT \
	-DFT_USE_RASTER \
	-DFT_USE_SMOOTH \
	-DFT_USE_TT \
	-DFT_USE_T1 \
	-DFT_USE_T42 \
	-DFT_USE_T1CID \
	-DFT_USE_CFF \
	-DFT_USE_OTV \
	-DFT_USE_GXV

SOURCES_C += \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/autofit/autofit.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftbase.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftbbox.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftbdf.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftbitmap.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftcid.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftdebug.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftfstype.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftgasp.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftglyph.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftgxval.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftinit.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftlcdfil.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftmm.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftotval.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftpatent.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftpfr.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftstroke.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftsynth.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftsystem.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/fttype1.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/base/ftwinfnt.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/bdf/bdf.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/bzip2/ftbzip2.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/cache/ftcache.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/cff/cff.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/cid/type1cid.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/gzip/ftgzip.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/lzw/ftlzw.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/pcf/pcf.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/pfr/pfr.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/psaux/psaux.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/pshinter/pshinter.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/psnames/psnames.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/raster/raster.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/sfnt/sfnt.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/smooth/smooth.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/truetype/truetype.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/type1/type1.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/type42/type42.c \
	$(CORE_DIR)/vendor/sdl2-libretro/libretro-tests/libs/sdl2_ttf-2.0.14/external/freetype-2.4.12/src/winfonts/winfnt.c

# SDL_ttf
# FLAGS += -I$(CORE_DIR)/vendor/sdl2-libretro/tests/SDL_ttf-2.0.11/VisualC/external/include
# SOURCES_C += $(CORE_DIR)/vendor/sdl2-libretro/tests/SDL_ttf-2.0.11/SDL_ttf.c

# SDL_stbimage
FLAGS += -I$(CORE_DIR)/vendor/Snippets

# STB
FLAGS += -I$(CORE_DIR)/vendor/stb

# TinySHA1
FLAGS += -I$(CORE_DIR)/vendor/TinySHA1

# cppcodec
FLAGS += -I$(CORE_DIR)/vendor/cppcodec

# FLAGS += -DVK_NO_PROTOTYPES

# Bullet3
# FLAGS += -I$(CORE_DIR)/vendor/bullet3/src
# SOURCES_CXX += $(wildcard \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletCollision/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletCollision/BroadphaseCollision/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletCollision/CollisionDispatch/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletCollision/CollisionShapes/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletCollision/Gimpact/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletCollision/NarrowPhaseCollision/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletDynamics/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletDynamics/Character/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletDynamics/ConstraintSolver/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletDynamics/Dynamics/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletDynamics/Featherstone/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletDynamics/MLCPSolvers/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/BulletDynamics/Vehicle/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/LinearMath/*.cpp \
# 	$(CORE_DIR)/vendor/bullet3/src/LinearMath/TaskScheduler/*.cpp \
# )
# FLAGS += -DBT_THREADSAFE=1
# FLAGS += -DBT_USE_DOUBLE_PRECISION=1
# FLAGS += -DCMAKE_BUILD_TYPE=Release
# FLAGS += -DBT_NO_PROFILE=1

# MemPlumber
# FLAGS += -I$(CORE_DIR)/vendor/memplumber
# SOURCES_CXX += $(wildcard \
# 	$(CORE_DIR)/vendor/memplumber/*.cpp \
# )

# Jolt Physics
FLAGS += -I$(CORE_DIR)/vendor/jolt
SOURCES_CXX += $(wildcard \
	$(CORE_DIR)/vendor/jolt/Jolt/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Skeleton/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/AABBTree/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/ObjectStream/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/TriangleSplitter/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Core/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Math/*.cpp \
    $(CORE_DIR)/vendor/jolt/Jolt/Physics/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Physics/Ragdoll/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Physics/Vehicle/*.cpp \
    $(CORE_DIR)/vendor/jolt/Jolt/Physics/Collision/*.cpp \
    $(CORE_DIR)/vendor/jolt/Jolt/Physics/Collision/Broadphase/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Physics/Collision/Shape/*.cpp \
    $(CORE_DIR)/vendor/jolt/Jolt/Physics/Body/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Physics/Constraints/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Physics/SoftBody/*.cpp \
    $(CORE_DIR)/vendor/jolt/Jolt/Physics/Character/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Geometry/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Utilities/*.cpp \
	$(CORE_DIR)/vendor/jolt/Jolt/Renderer/*.cpp \
)
# Disable Jolt debug renderer to silence debug drawing and reduce overhead
# FLAGS += -DJPH_DEBUG_RENDERER=1

# tracy
# FLAGS += -I$(CORE_DIR)/vendor/tracy/public
# SOURCES_CXX += $(wildcard \
# 	$(CORE_DIR)/vendor/tracy/public/*.cpp \
# )
# FLAGS += -DTRACY_ENABLE

# Magnum
#FLAGS += -I$(CORE_DIR)/vendor/magnum/src/Magnum/Trade
#FLAGS += -I$(CORE_DIR)/vendor/corrade/src/Corrade/PluginManager
#FLAGS += -I$(CORE_DIR)/vendor/corrade/src/Corrade/Containers
# FLAGS += -DCORRADE_BUILD_STATIC
# FLAGS += -I$(CORE_DIR)/vendor/corrade_x64-windows/include
# FLAGS += -I$(CORE_DIR)/vendor/magnum_x64-windows/include
# SOURCES_CXX += $(wildcard \
# 	./vendor/corrade/src/Corrade/Containers/*.cpp \
# 	./vendor/corrade/src/Corrade/PluginManager/*.cpp \
# 	./vendor/magnum/src/Magnum/Trade/*.cpp)

# RapidJSON
FLAGS += -I$(CORE_DIR)/vendor/rapidjson/include/rapidjson

FLAGS += -DLOAD_PNG

# ChaiScript
ifeq ($(HAVE_CHAISCRIPT),)
	FLAGS += -I$(CORE_DIR)/vendor/chaiscript/include
	FLAGS += -I$(CORE_DIR)/vendor/ChaiScript_Extras/include
	FLAGS += -D__HAVE_CHAISCRIPT__
	# LEAK FIX: Enable threading to activate thread-local pooling (80-90% reduction in allocations)
	FLAGS += -DCHAISCRIPT_NO_DYNLOAD
	FLAGS += -DCHAISCRIPT_EXTRAS_MATH_SKIP_ADVANCED
	# LEAK FIX: Disable standard allocator to enable Boxed_Value pooling (reduces allocation overhead 80-90%)
	FLAGS += -UCHAISCRIPT_USE_STD_MAKE_SHARED
endif

OBJECTS += $(SOURCES_C:.c=.o) $(SOURCES_CXX:.cpp=.o) $(SOURCES_S:.S=.o) $(SOURCES_M:.m=.o)

LDFLAGS +=  $(fpic) $(SHARED) $(EXTRA_LDF)

WARNINGS :=

# Windows: Fix retro_common_api.h
ifeq ($(system_platform), win)
	FLAGS += -DPRId64=I64d -DPRIu64=I64u -DPRIuPTR=Iu
endif
